Update updater-script

diff --git a/META-INF/com/google/android/updater-script b/META-INF/com/google/android/updater-script
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -14,31 +14,25 @@ source "$CONFIG_FILE"
 #       along with a timeout mechanism for user selections
 
 print_line = # Prints a banner line using CHAR_WIDTH length of '-' (or custom character), wrapped with '*' on both ends
-print_centered "Welcome to WinInstaller for $DEVICE_NAME"
+print_centered "Welcome to Windows Installation on $DEVICE_NAME"
 print_centered "Version: $WI_VERSION"
-print_centered "Build date: $BUILD_DATE"
+print_centered "Build Date: $BUID_DATE"
 print_centered "Made by: Kumar_Jy & ArKT"
 print_centered "Help and suggestions by: Sog, Andre_grams"
 print_centered "Drivers & UEFI: $MAINTAINER"
 print_line =
 verify_device
-aio_progress 0.5 10   # start progress from 0% to 50% in 10 seconds
-print_centered "Verifying file integrity"
-file_checksum
-print_centered "File verification done"
-print_line
-print_centered "Verifying required partitions"
+print_centered "Verifying required Partitions"
 verify_part
 print_line # Prints a banner line using CHAR_WIDTH length of '-' (or custom character), wrapped with '*' on both ends
-print_centered "Checking battery status"
+print_centered "Checking Battery Status"
 if verify_battery; then
 print_centered "Battery percentage is sufficient: $CURRENT_BATTERY%"
 else
-   abort "Battery is below $REQUIRED_BATTERY%, exiting..."
+   abort "Battery is only $CURRENT_BATTERY% Charged, Charge it at list $REQUIRED_BATTERY% ..."
 fi
 print_line
 print_centered "Fixing GPT"
-aio_progress 0.5 0    # instantly moves progress back to 50% (for reset or rewind)
 aio_progress 0.5 10   # start progress from 0% to 50% in 10 seconds
 run_gptfix
 print_line
@@ -51,18 +45,18 @@ if is_windows_installed; then
 print_centered "Windows is already installed"
 print_line
 aio_progress 0.5 0    # instantly moves progress back to 50% (for reset or rewind)
-winask=("Option 1: Driver update/install only" "Option 2: Windows re-install (with format)")
+winask=("Option 1: Driver Update/install only" "Option 2: Windows re-install (with format)")
 navigate_menu_timeout "${winask[@]}"
 case "$selection" in
   0)
     if is_partition_rw; then
     print_line
     print_centered "Skipping format and copy steps"
-    print_centered "and processing for driver installation"
+    print_centered "and processing for Drivers Installation"
     else
     print_exit
-    print_centered "Error: Partition is read-only"
-    nl_print_centered "Go to Windows then reboot into Android and try again"
+    print_centered "Error: Partition is Read-Only"
+    nl_print_centered "Goto Windows then reboot to Android and try again"
     umount "$WIN_PATH"
     exit 1
     fi
@@ -74,36 +68,20 @@ case "$selection" in
     print_centered "You chose to reinstall Windows"
     print_centered "Proceeding with formatting and installation"
     print_line
-    print_centered "Searching for Windows image (.wim or .esd)"
-    win_esd_search
-    print_line
-    print_centered "Verifying Windows edition"
-    find_index
-    print_line
-    print_centered "Installing $SELECTED_EDITION...."
-    format_win
-    "$UPD_TEMP_FOLDER/wimlib-imagex" apply "$WIN_IMAGE" "$SELECTED_INDEX" "$WIN_PATH"
+    Windows_Installation
     ;;
   esac
 else
 aio_progress 0.5 0    # instantly moves progress back to 5% (for reset or rewind)
 aio_progress 0.9 80   # moves progress from 5% to 90% in 80 seconds
-print_centered "Windows is not yet installed"
-print_centered "Proceeding with Windows installation"
+print_centered "Windows is not already installed"
+print_centered "Proceeding with Windows Installation"
 print_line
-print_centered "Searching for Windows image"
-win_esd_search
-print_line
-print_centered "Verifying Windows edition"
-find_index
-print_line
-print_centered "Installing $SELECTED_EDITION...."
-format_win
-"$UPD_TEMP_FOLDER/wimlib-imagex" apply "$WIN_IMAGE" "$SELECTED_INDEX" "$WIN_PATH"
+Windows_Installation
 fi
 if ! is_windows_installed; then
 print_exit
-print_centered "$SELECTED_EDITION Failed to install "
+print_centered "$SELECTED_EDITION Fail to install "
 print_centered "ESD/WIM file may be corrupted..."
 nl_print_centered "Reboot to Android and check the ESD/WIM file."
 umount "$WIN_PATH"
@@ -114,9 +92,13 @@ fi
 aio_progress 0.5 0    # instantly moves progress back to 50% (for reset or rewind)
 aio_progress 0.95 50  # moves progress from 50% to 95% in 50 seconds
 print_line
-print_centered "Extracting installation files";
-package_extract_folder "installer" "$WIN_MOUNT_FOLDER"
-ESP_PART_NO=$(realpath "$BASE_PATH/esp" | grep -o '[0-9]*$')
+print_centered "Extracting Installation File";
+package_extract_folder "installer" "$WIN_MOUNT_FOLDER" || { abort "Error Extracting Installation File"; }
+print_line
+print_centered "Verifying Checksum for Installer"
+(cd $WIN_MOUNT_FOLDER/installer && sha256sum -c sha256sum) || { abort "Checksum verification failed, zip file is croupted, download it again"; }
+print_centered "Checksum verification success"
+print_line
 for var in ESP_PART_NAME ESP_PART_NO DEVICE_NAME WI_VERSION BUID_DATE SECURE_BOOT MAINTAINER; do
   eval value=\$$var
   sed -i "s|^set $var=.*|set $var=$value|" "$PE_INSTALLER"
@@ -125,20 +107,20 @@ package_extract_folder "ToolBox" "$WIN_MOUNT_FOLDER"
 package_extract_file "woahelper.apk" "/sdcard/woahelper.apk"
 print_line
 print_centered "Flashing UEFI image"
-rm /sdcard/UEFI/*.img
+rm -rf /sdcard/UEFI
 mkdir -p /sdcard/UEFI
 dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="/sdcard/UEFI/uefi.img" bs=1M || { abort "Error copying uefi.img"; }
-dd if="/sdcard/backup/boot$(getprop ro.boot.slot_suffix).img" of="$WIN_MOUNT_FOLDER/boot.img" bs=1M 2>/dev/null || dd if="/sdcard/backup/boot.img" of="$WIN_MOUNT_FOLDER/boot.img" bs=1M || { abort "Error copying boot.img in Windows"; }
-dd if="$WIN_MOUNT_FOLDER/installer/pe.img" of="$BASE_PATH/esp" bs=1M || { abort "Error flashingh WinPE.img"; }
-dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot$(getprop ro.boot.slot_suffix)" bs=1M 2>/dev/null || dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot" bs=1M || { abort "Error flashing uefi on boot partition"; }
+dd if="/sdcard/backup/boot$(getprop ro.boot.slot_suffix).img" of="$WIN_MOUNT_FOLDER/boot.img" bs=16M || { abort "Error copying boot.img in Windows"; }
+dd if="$WIN_MOUNT_FOLDER/installer/pe.img" of="$BASE_PATH/esp" bs=16M || { abort "Error flashingh WinPE.img"; }
+dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot$(getprop ro.boot.slot_suffix)" bs=1M || { abort "Error flashing uefi on boot partition"; }
 umount "$WIN_PATH" "$ESP_PATH"
 sleep 1
 print_line =
-print_centered "Flashing completed, now press "Reboot system""
+print_centered "Flashing Completed, Now reboot to system"
 print_centered "Installation will start automatically"
 print_line =
-print_centered "If it fails, don't flash it again"
-print_centered "Ask for help on Telegram: @wininstaller"
+print_centered "If it fails, Don't Flash it again"
+print_centered "ask for help on Telegram: @wininstaller"
 print_centered "Thanks to all WOA Developers & Maintainers"
 print_line =
 exitask=("Option 1: Reboot device" "Option 2: Exit")
@@ -146,14 +128,14 @@ navigate_menu_timeout "${exitask[@]}"
 case "$selection" in
   0)
     print_line
-    print_centered "Your device will reboot now!"
+    print_centered "your device will reboot now!"
     print_line
     sleep 1
 	  reboot
     ;;
   1)
     print_line
-    print_centered "WinInstaller nuke done!"
+    print_centered "WinInstaller nuked done!"
     print_line
     exit
     ;;
