Added ui_print in center, gpt_fix to run automatically and reboot selection

diff --git a/META-INF/com/google/android/updater-script b/META-INF/com/google/android/updater-script
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -5,7 +5,8 @@
 # Made for Windows Installation on WOA Devices 
 #
 
-#=======================Configrations=======================
+#================================Configrations===============================
+
 DEVICE_CODE="nabu" # Check and verify device with its codename
 BASE_PATH="/dev/block/by-name"  # Base path to named partition symlinks
 WIN_PATH="$BASE_PATH/win"  # Windows partition block name
@@ -17,102 +18,94 @@ REQUIRED_BATTERY=50  # Minimum required battery percentage to proceed
 PARTITION_BACKUP="boot dtbo vendor_boot fsc fsg modemst1 modemst2 persist" # set partiiton to backup auto handgle A/B non A/B device
 WIN_PART_NAME="WINNABU"  # Partiton name for format
 WINDOWS_EDITIONS=(
-    "Windows 11 Pro"
-    "Windows 11 IoT Enterprise LTSC"
-    "Windows 11 Enterprise"
-    "Windows 11 Home"
-    "Windows 10 Pro"
-    "Windows 10 Home"
+"Windows 11 Pro"
+"Windows 11 IoT Enterprise LTSC"
+"Windows 11 Enterprise"
+"Windows 11 Home"
+"Windows 10 Pro"
+"Windows 10 Home"
 )
-BANNER_EXIT="*---------------------Error!--------------------*"
-BANNER_LINE="*-----------------------------------------------*"
-#===========================================================
+CHAR_WIDTH=49 #for max character in one line, if exceed then it auto wrapped to next line
+BANNER_EXIT="*---------------------Error!----------------------*"
+BANNER_LINE="*-------------------------------------------------*"
+BANNER_DLINE="*=================================================*"
 
-ui_print "*===============================================*"
-ui_print "*Welcome to Windows Installation on Xiaomi Pad 5*"
-ui_print "*        Version: WinInstaller_Nabu_R8.2.5      *"
-ui_print "*        Date   : 07-May-2025                   *"
-ui_print "*        Made by: Kumar_Jy & ArKT               *"
-ui_print "*   Help and suggestions by: Sog, Andre_grams   *"
-ui_print "*Drivers & UEFI: Project-Aloha,map220v,remtrik..*"
-ui_print "*===============================================*"
+#=======================UI-Prints=funtions-executions========================
+print_dline
+print_centered "Welcome to Windows Installation on Xiaomi Pad 5"
+print_centered "Version: WinInstaller_Nabu_R8.2.5"s
+print_centered "Build Date: 09-May-2025"
+print_centered "Made by: Kumar_Jy & ArKT"
+print_centered "Help and suggestions by: Sog, Andre_grams"
+print_centered "Drivers & UEFI: Project-Aloha,map220v,remtrik.."
+print_dline
 verify_device "$DEVICE_CODE"
-ui_print "*           Verifying Partition Size            *"
+print_centered "Verifying required Partitions"
 verify_part
-ui_print "$BANNER_LINE"
-ui_print "*            Checking Battery Status            *"
+print_line
+print_centered "Checking Battery Status"
 if verify_battery; then
-    ui_print "      Battery percentage is sufficient: $CURRENT_BATTERY%"
+print_centered "Battery percentage is sufficient: $CURRENT_BATTERY%"
 else
-    abort "        Battery is below $REQUIRED_BATTERY%, exiting..."
+   abort "Battery is below $REQUIRED_BATTERY%, exiting..."
 fi
-ui_print "$BANNER_LINE"
-ui_print "*                   Fixing GPT                  *"
+print_line
+print_centered "Fixing GPT"
 aio_progress 0.5 10
-setup_gdisk
-#to-do loop in all available device 
-for i in a b c d e f; do  
-    DEVICE="/dev/block/sd$i"
-    run_gdisk "$DEVICE"
-done
-ui_print "$BANNER_LINE"
-ui_print "*  Extracting boot and modem to /sdcard/backup  *"
+run_gptfix
+print_line
+print_centered "Extracting boot and modem to /sdcard/backup"
 backup_partitions $PARTITION_BACKUP
-ui_print "$BANNER_LINE"
-ui_print "*   Checking if Windows is already installed    *"
-ui_print "$BANNER_LINE"
+print_line
+print_centered "Checking if Windows is already installed"
+print_line
 aio_progress 0.1 0
 aio_progress 0.9 80
-setup_wimlib
 if is_windows_installed; then
-    ui_print "*          Windows is already installed         *"
-    #to-do add volume button selection to choose re-install again with windows format or continue
-    if is_partition_rw; then
-        ui_print "*         Skipping format and copy steps        *"
-        ui_print "*    and processing for Drivers Installation    *"
-    else
-        ui_print " "
-        ui_print "$BANNER_EXIT"
-        ui_print "          Error: Partition is Read-Only         "
-        ui_print "Goto Windows then reboot to Android and try again"
-        ui_print " "
-        umount "$win_path"
-        exit 1
-    fi
+print_centered "Windows is already installed"
+#to-do add volume button selection to choose re-install again with windows format or continue
+if is_partition_rw; then
+print_centered "Skipping format and copy steps"
+print_centered "and processing for Drivers Installation"
 else
-    ui_print "*        Windows is not already installed       *"
-    ui_print "*      Proceeding with Windows Installation     *"
-    ui_print "$BANNER_LINE"
-    ui_print "*           Searching for Windows Image         *"
-    win_esd_search
-    ui_print "$BANNER_LINE"
-    ui_print "*           Verifying Windows Edition           *"
-    find_index
-    ui_print "$BANNER_LINE"
-    ui_print "   Installing $SELECTED_EDITION ...."
-    format_win
-    "$UPD_TEMP_FOLDER/wimlib-imagex" apply "$WIN_IMAGE" "$SELECTED_INDEX" "$WIN_PATH"
+print_exit
+print_centered "Error: Partition is Read-Only"
+nl_print_centered "Goto Windows then reboot to Android and try again"
+umount "$WIN_PATH"
+exit 1
 fi
-
+else
+print_centered "Windows is not already installed"
+print_centered "Proceeding with Windows Installation"
+print_line
+print_centered "Searching for Windows Image"
+win_esd_search
+print_line
+print_centered "Verifying Windows Edition"
+find_index
+print_line
+print_centered "Installing $SELECTED_EDITION...."
+format_win
+"$UPD_TEMP_FOLDER/wimlib-imagex" apply "$WIN_IMAGE" "$SELECTED_INDEX" "$WIN_PATH"
+fi
 if ! is_windows_installed; then
-    ui_print " "
-    ui_print "$BANNER_EXIT"
-    ui_print "Failed to install $SELECTED_EDITION, ESD/WIM file may be corrupted..."
-    ui_print "Reboot to Android and check the ESD/WIM image."
-    ui_print " "
-    umount "$win_path"
-    exit 1
+print_exit
+print_centered "$SELECTED_EDITION Fail to install "
+print_centered "ESD/WIM file may be corrupted..."
+nl_print_centered "Reboot to Android and check the ESD/WIM file."
+umount "$WIN_PATH"
+exit 1
 fi
 aio_progress 0.5 0
 #After this idk if i'll do modular, but not need ig, idk also already added handle non A/B device in oneliner like before
 aio_progress 0.95 50
-ui_print "$BANNER_LINE"
-ui_print "*         Extracting Installation File          *";
+print_line
+print_centered "Extracting Installation File";
 package_extract_folder "installer" "$WIN_MOUNT_FOLDER"
 package_extract_folder "ToolBox" "$WIN_MOUNT_FOLDER"
 package_extract_file "woahelper.apk" "/sdcard/woahelper.apk"
-ui_print "$BANNER_LINE"
-ui_print "*               Flashing UEFI image             *"
+print_line
+print_centered "Flashing UEFI image"
 rm /sdcard/UEFI/*.img
 mkdir -p /sdcard/UEFI
 dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="/sdcard/UEFI/uefi.img" bs=1M || { abort "Error copying uefi.img"; }
@@ -121,16 +114,24 @@ dd if="$WIN_MOUNT_FOLDER/installer/pe.img" of="$BASE_PATH/esp" bs=1M || { abort 
 dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot$(getprop ro.boot.slot_suffix)" bs=1M 2>/dev/null || dd if="$WIN_MOUNT_FOLDER/installer/uefi.img" of="$BASE_PATH/boot" bs=1M || { abort "Error flashing uefi on boot partition"; }
 umount "$WIN_PATH" "$ESP_PATH"
 sleep 1
-ui_print "*===============================================*"
-ui_print "*   Flashing Completed, Now reboot to system    *"
-ui_print "*                                               *"
-ui_print "*     Installation will start automatically     *"
-ui_print "*                                               *"
-ui_print "*      If it fails, Don't Flash it again        *"
-ui_print "*                                               *"
-ui_print "*    ask for help on Telegram: @wininstaller    *"
-ui_print "*                                               *"
-ui_print "*   Thanks to all WOA Developers & Maintainers  *"
-ui_print "*===============================================*"
-#to-do add volume button selection to choose to restart or exit
-exit
+print_dline
+print_centered "Flashing Completed, Now reboot to system"
+print_centered "Installation will start automatically"
+print_dline
+print_centered "If it fails, Don't Flash it again"
+print_centered "ask for help on Telegram: @wininstaller"
+print_centered "Thanks to all WOA Developers & Maintainers"
+print_dline
+options=("Option 1: Reboot device" "Option 2: Exit")
+navigate_menu "${options[@]}"
+case "$selection" in
+  0)
+    ui_print "rebooting now!"
+    sleep 1
+	reboot
+    ;;
+  1)
+    ui_print " "
+    exit
+    ;;
+esac
